apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-nginx-server
  labels: 
   app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
        annotations:
           {{- range $key, $value := .Values.podAnnotations }}
           {{ $key }}: {{ $value }}
           {{- end }}
      {{- end }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        env:
          - name: foo
            value: bar
            {{- if .Values.customVar }}
          - name: CUSTOM_BAR
            value: {{ .Values.customVar }}
            {{- end }}